name: TimeHUD
version: 1.1.0
main: com.server.timehud.TimeHUD
api-version: "1.20"
author: Server
description: Oyuncu HUD'unda sunucu saatini gösterir
commands:
  timehud:
    description: Zaman HUD'unu aç/kapat
    usage: /timehud [on|off|reload|help]
    aliases: [zamanHUD, saat]
permissions:
  timehud.toggle:
    description: Zaman HUD'unu açma/kapatma izni
    default: true
  timehud.reload:
    description: Yapılandırmayı yeniden yükleme izni
    default: op
